const DEFAULT_TITLE = "Student Coupon";
const DEFAULT_DESCRIPTION =
  "A mobile first student discount coupon finding app";

const CONSTANTS = {
  DEFAULT_TITLE: DEFAULT_TITLE,
  DEFAULT_AUTHOR: "CMPUT 401 Group",
  DEFAULT_DESCRIPTION: DEFAULT_DESCRIPTION,
  DEFAULT_KEYWORDS: ["next", "coupon", "student"],
  DEFAULT_SITE_NAME: "Student Coupons",
  DEFAULT_BASE_URL: "http://localhost:3000",
  DEFAULT_PREVIEW_IMG: "",
  DEFAULT_TWITTER_TITLE: DEFAULT_TITLE,
  DEFAULT_TWITTER_DESCRIPTION: DEFAULT_DESCRIPTION,
  DEFAULT_GOOGLE_ANALYTICS: "",
};

export default CONSTANTS;
